[package]
name = "single-page-web-server-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
md5 = "0.7"
httpdate = "1.0"
hyper = { version = "0.14", features = ["full"] }
tokio = { version = "1", features = ["full"] }