name: Release

permissions:
  contents: write
  packages: write

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Create Release
        id: create_release
        uses: ncipollo/release-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag: ${{ github.ref }}
          name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false

  build-and-upload:
    needs: create-release
    strategy:
      matrix:
        include:
          - target: x86_64-unknown-linux-gnu
            os: ubuntu-latest
            asset_name: single-page-web-server-rs-linux-amd64
            binary_name: single-page-web-server-rs
          - target: x86_64-apple-darwin
            os: macos-latest
            asset_name: single-page-web-server-rs-darwin-amd64
            binary_name: single-page-web-server-rs
          - target: aarch64-apple-darwin
            os: macos-latest
            asset_name: single-page-web-server-rs-darwin-arm64
            binary_name: single-page-web-server-rs
          - target: x86_64-pc-windows-msvc
            os: windows-latest
            asset_name: single-page-web-server-rs-windows-amd64.exe
            binary_name: single-page-web-server-rs.exe
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      
      - name: Install Rust toolchain
        shell: bash
        run: |
          rustup default stable
          rustup target add ${{ matrix.target }}

      - name: Build
        shell: bash
        run: |
          cargo build --release --target ${{ matrix.target }}

      - name: Rename and strip binary
        shell: bash
        run: |
          cd ./target/${{ matrix.target }}/release
          cp "${{ matrix.binary_name }}" "${{ matrix.asset_name }}"
          strip "${{ matrix.asset_name }}"

      - name: Upload Release Asset
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: ./target/${{ matrix.target }}/release/${{ matrix.asset_name }}